# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlflow-ui
  template:
    metadata:
      labels:
        app: mlflow-ui
    spec:
      containers:
      - name: mlflow-ui
        image: mlflow-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlflow-ui-service
spec:
  type: NodePort
  selector:
    app: mlflow-ui
  ports:
    - port: 5000
      targetPort: 5000
