apiVersion: batch/v1
kind: Job
metadata:
  name: iris-train
spec:
  template:
    spec:
      containers:
      - name: iris-train
        image: iris-train:latest
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 2
